### ISSUE TITLE
Global Text Changes: Report naming

### ISSUE THREAD

**Issue by tashalouizamc** [Project-Counter/cop5#126]
Within Release 5.1, report naming conventions to be amended. 'Master Report' renamed as 'COUNTER Report', 'Standard View' renamed as 'Standard View of COUNTER Report'. 

**Details**
Master Report(s) > Report(s), including 
- Platform Master Report > Platform Report
- Title Master Report > Title Report
- Database Master Report > Database Report
- Item Master Report > Item Report

Standard View(s) > Standard View(s) of COUNTER Report(s)
All reports > COUNTER Reports and Standard Views of COUNTER Reports

Where ‘reports’ is NOT used as a proper noun, it should not be changed

**Comment by berndoberknapp** [comment]
The sample reports still need to be updated.

**Comment by tashalouizamc** [comment]
> The sample reports still need to be updated.

Covered in #154 and #173
