### ISSUE TITLE
Global Text Changes: Dating

### ISSUE THREAD

**Issue by tashalouizamc** [Project-Counter/cop5#127]
Within Release 5.1, update example years to 2023 where appropriate. 

**Details**
Examples and sample reports are presented at various points in the COP, many with dates in 2017-2019. Proposed change to 2023 in all relevant cases.

**Comment by berndoberknapp** [comment]
The sample reports still need to be updated.

**Comment by tashalouizamc** [comment]
> The sample reports still need to be updated.

Covered in #154 and #173
