### ISSUE TITLE
Versioning: use of explicit versioning

### ISSUE THREAD

**Issue by tashalouizamc** [Project-Counter/cop5#131]
In R5.1 the COP will transition to use of Explicit Versioning, a four-digit numbering system in the structure _Release.Breaking.Feature.Fix_, where “Breaking” indicates changes that are not backwards compatible, “Feature” indicates new features or extensions that are backwards compatible, and “Fix” is used for typographic corrections and similar small amendments. Explicit Versioning thus allows for us to change the Release number where changes are so comprehensive that Release 5 would no longer apply.

Affected sections of the COP:
- Section 1.1.7 Versions
- Section 12 Continuous Maintenance, specifically 12.3.4 Version and Change Control and 12.4 Implementation Schedule

**Comment by berndoberknapp** [comment]
Reopening issue since the commit was deleted.
