### ISSUE TITLE
Components move from Required to Optional

### ISSUE THREAD

**Issue by tashalouizamc** [Project-Counter/cop5#135]
Release 5 introduced “Components” as subunits of pieces of content - for example, a dataset may be a component of a journal article. Feedback from repositories and publishers suggests that few users actively wish to analyse usage at this level of detail, while the requirement to deliver such granular information makes generating an Item Report very difficult. In R5.1 we are making Components optional - that is, allowing report providers to deny a request for Components by delivering an Exception.

Affects
- Section 3.2.2 Report Body, specifically the subsection on Component Item Description and Identifiers
- Section 3.3.8 Report Filters and Report Attributes, table 3.x
- Section 4.4.2 Column Headings/Elements and 4.4.3 Filters and Attributes, both for Item Reports
- Appendix A, Glossary of Terms
- Appendix F, Handling Errors and Exceptions

**Comment by tashalouizamc** [comment]
Note for @berndoberknapp - I'm not sure of the preferred handling error for cases where components are requested but not supported by the report provider.

**Comment by berndoberknapp** [comment]
I would suggest a new Exception 3063 (Components Not Supported) for this case.

**Comment by tashalouizamc** [comment]
NOTE that this change will be reflected in sample reports covered in linked issues #154  and #173
