### ISSUE TITLE
Fix Other_Free_To_Read use in Master Title Reports

### ISSUE THREAD

**Issue by berndoberknapp** [Project-Counter/cop5#2]
Other_Free_To_Read is listed as Access_Type filter for TR in Table 4.l, but Other_Free_To_Read is only permitted for Host_Types Repository and Data_Repository which don't have to provide TR. Therefore Other_Free_To_Read should be removed from Table 4.l and a note added to the definition of Other_Free_To_Read in Table 3.u that this Access_Type may be used by repositories if they provide TR.

**Comment by berndoberknapp** [comment]
Another option to fix this issue would be to keep Other_Free_To_Read in Table 4.l and explain that this value is only permitted for Host_Types Repository and Data_Repository if they provide TR (which isn't a requirement for these Host_Types, the TR in this case would be an IR aggregated on the title level). Currently the tables only list the requirements, so for consistency the approach also would have to be changed in other cases where something can be done optionally, for example for Host_Type Full_Content_Database which can use Data_Type Database in TR if that report is provided (see Table 3.p and the note below the table).

**Comment by lorraineestelle** [comment]
Dear Bernd - just a test

**Comment by tashalouizamc** [comment]
I lean towards the first option - removing Other_Free_To_Read from the description of TR in 4.l

**Comment by lorraineestelle** [comment]
I agree, this has caused some confusion.
