### ISSUE TITLE
COUNTER API (formerly sushi)

### ISSUE THREAD

**Issue by COUNTERMetrics** [Project-Counter/cop5#248]
As part of our efforts to use plain language, we will update the Code to reflect current terminology: COUNTER_API (formerly sushi) in place of COUNTER_SUSHI_API.

We will add a note in the Code to explain that our previous use of the terms SUSHI or COUNTER_SUSHI_API are references to SUSHI-Lite – the RESTful version of SUSHI that was described in an unpublished NISO Technical Report.

The heading for section 8 will be changed from ‘SUSHI for automated report harvesting’ to ‘COUNTER API for automated report harvesting’.

We will edit section 8.1 to read
'Report providers SHOULD use the same COUNTER_API base URL for all releases. For example, if the URL for requesting the list of reports is https://example.org/counter/reports in R5, it should be https://example.org/counter/r51/reports in R5.1, so that the base URL for both releases is https://example.org/counter."

Note that it may not be possible for us to amend our stoplight URLs at this point, so the old counter-sushi-api slug may remain in place for this Release.

**Comment by berndoberknapp** [comment]
We have to keep the old Stoplight.io slug counter-sushi-api, because changing the slug will break all published URLs.
